# Generated by Django 4.2.3 on 2023-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Not defined', max_length=100),
            preserve_default=False,
        ),
    ]
