# Generated by Django 4.2.3 on 2023-08-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import market.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AddField(
            model_name='property',
            name='added_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic',
            field=models.ImageField(blank=True, null=True, upload_to=market.models.property_pic_path),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='market.propertytype'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('Plot', 'P'), ('Shop', 'S'), ('House', 'H')], max_length=40),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Sindh', 'S'), ('Punjab', 'P'), ('Balochistan', 'B'), ('KPK', 'K')], max_length=40)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_for_area', to='market.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_for_city', to='market.city')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.location'),
        ),
    ]
