# Generated by Django 4.2.3 on 2023-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_property_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='size_unit',
            field=models.IntegerField(blank=True, choices=[('Square feet', 'sq.ft'), ('Square meters', 'sq.m'), ('Marla', 'marla'), ('Kanal', 'kanal')], null=True),
        ),
    ]
