# Generated by Django 4.2.3 on 2023-08-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_property_size_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('Square feet', 'sq.ft'), ('Square meters', 'sq.m'), ('Marla', 'marla'), ('Kanal', 'kanal')], max_length=100, null=True),
        ),
    ]
