# Generated by Django 4.2.3 on 2023-08-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_property_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='province',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='market.area'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_city', to='market.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, choices=[('Sindh', 'S'), ('Punjab', 'P'), ('Balochistan', 'B'), ('KPK', 'K')], max_length=40, null=True),
        ),
    ]
