# Generated by Django 4.2.3 on 2023-08-27 14:17

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_pic',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Allowed size is 50MB', null=True, upload_to='PN_files/%Y/%m/%d/', validators=[market.models.validate_file_size], verbose_name='Files')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_pics', to='market.property')),
            ],
        ),
    ]
